# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VCS-Hms
version:      0.04
version_from: Hms.pm
installdirs:  site
requires:
    Sort::Versions:                0
    Test::More:                    0
    VCS:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
